server:
  port: 8082
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://www.aaa.com:8080/eureka,http://www.bbb.com:8081/eureka

