server:
  port: 9090

spring:
  application:
    name: server-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: true
    fetch-registry: true
